# Generated by Django 4.2.5 on 2023-09-28 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время / по умолч: сейчас'),
        ),
    ]
