# Generated by Django 4.2.5 on 2023-09-29 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=datetime.time(3, 42, 57, 972329), verbose_name='Время / по умолч: сейчас'),
        ),
    ]
