# Generated by Django 4.2.5 on 2023-10-02 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=datetime.time(6, 30, 47, 81312), verbose_name='Время / по умолч: сейчас'),
        ),
    ]
