# Generated by Django 4.2.5 on 2023-10-23 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=datetime.time(5, 3, 11, 952507), verbose_name='Время / по умолч: сейчас'),
        ),
    ]
